### ISSUE TITLE
New URL and errors finding torrents

### ISSUE THREAD

**Issue by antipiot** [Ripolin/potatoygg#13] opened 2018-11-13 19:07 UTC
Hello!

Wanted to report that Yggtorrent URL changed again to www9 :-)

Anyway: i've tried to change the URL in ygg.py from www6 to www9 but i'm facing new errors:

`11-13 20:01:49 ERROR[tato.core.plugins.ygg.ygg] Failed searching release from YGG: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/ygg/ygg.py", line 189, in _searchOnTitle for link in soup.find(class_='results').find_all( AttributeError: 'NoneType' object has no attribute 'find_all'
11-13 20:01:50 ERROR[tato.core.plugins.ygg.ygg] Failed searching release from YGG: Traceback (most recent call last): File "/app/couchpotato/couchpotato/core/plugins/ygg/ygg.py", line 189, in _searchOnTitle for link in soup.find(class_='results').find_all( AttributeError: 'NoneType' object has no attribute 'find_all' `

Does somebody know what's up?

**Comment by clemsail** [comment] 2018-11-17 11:55
I've the same errors, but no issues

**Comment by Ripolin** [comment] 2018-11-17 13:24
Duplicate of #14

**Closed as completed by Ripolin** 2018-11-17 13:24 UTC
Labels: duplicate
